services:
  app:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: >
        CMD-SHELL python -c "import sys,urllib.request;
        sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').getcode() == 200 else sys.exit(1)"
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s